# Globale Einstellungen (falls benötigt)
dataset: fmcw        # Neuer Parameter für deinen Datensatz

MODEL:
  arch: dgcnn
  num_matrices: [8, 8, 8, 8]
  k_neighbors: 20
  calc_scores: softmax

TRAIN:
  exp_name: fmcw_pseudo_train
  num_points: 1024
  pt_norm: False
  batch_size: 16
  test_batch_size: 8
  epochs: 10
  lr: 0.1
  momentum: 0.9
  dropout: 0.5         
  eval: False          
  no_cuda: False       
  workers: 1           
